apiVersion: v1
kind: Service
metadata:
  name: tf-ps0
  labels:
    tf-ps: "0"
spec:
  type:  ClusterIP
  ports:
  - name: tensorboard
    port: 6006
  - name: grpcport
    port: 2222
  - name: alluxioport
    port: 19998
  selector:
    tf-ps: "0"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tf-ps0
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tf-ps: "0"
        name-prefix: "tf"
        job: "ps"
    spec:
      containers:
      - name: tf-ps0
        image: alluxio/alluxio-tensorflow:1.7.0-1.3.0-gpu
        command: ["/entrypoint.sh"]
        args: ["master"]
        ports:
        - containerPort: 6006
          name: tensorboard
        - containerPort: 2222
          name: grpcport
        - containerPort: 19998
          name: alluxioport
        env:
         - name: ALLUXIO_UNDERFS_ADDRESS
           value: "wasb://$yourcontainername$@$yourstorageaccountname$.blob.core.windows.net/"
         - name: FS_AZURE_ACCOUNT_KEY_$yourstorageaccountname$_BLOB_CORE_WINDOWS_NET
           value: $yourstorageaccountkey$
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: 2
        volumeMounts:
        - mountPath: /usr/local/nvidia
          name: nvidia-driver
        - mountPath: /joy
          name: shared
        - mountPath: /imagenetdata
          name: imagenet
        - mountPath: /imagenetazurefiles
          name: imagenetazure
        - mountPath: /etc/resolv.conf
          name: resolv
        securityContext:
          privileged: true
          capabilities:
             add: ["SYS_ADMIN"]
      nodeSelector:
        nodedesc: gpunode0
      volumes:
      - name: nvidia-driver
        hostPath:
          path: /opt/nvidia-driver/current
      - name: shared
        hostPath:
          path: /home/dlwsadmin
      - name: imagenet
        hostPath:
          path: /mnt/imagenet-data
      - name: resolv
        hostPath:
          path: /etc/resolv.conf
      - name: imagenetazure
        azureFile:
          secretName: azurefile-secret
          shareName: imagenet
          readOnly: false
---
