apiVersion: v1
kind: Service
metadata:
  name: tf-worker0
  labels:
    tf-worker: "0"
spec:
  type:  ClusterIP
  ports:
  - name: tensorboard
    port: 6006
  - name: grpcport
    port: 2222
  - name: alluxioport
    port: 19998
  selector:
    tf-worker: "0"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tf-worker0
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tf-worker: "0"
        name-prefix: "tf"
        job: "worker"
    spec:
      containers:
      - name: tf-worker0
        image: alluxio/alluxio-tensorflow:1.7.0-1.3.0-gpu
        command: ["/entrypoint.sh"]
        args: ["worker"]
        ports:
        - containerPort: 6006
          name: tensorboard
        - containerPort: 2222
          name: grpcport
        - containerPort: 19998
          name: alluxioport
        env:
        - name: ALLUXIO_MASTER_HOSTNAME
          value: "$yourpsserverip$"
        - name: ALLUXIO_RAM_FOLDER
          value: "/opt/ramdisk"
        - name: ALLUXIO_WORKER_MEMORY_SIZE
          value: "10GB"
        - name: ALLUXIO_UNDERFS_ADDRESS
          value: "wasb://$yourcontainername$@$yourstorageaccountname$.blob.core.windows.net/"
        - name: FS_AZURE_ACCOUNT_KEY_$yourstorageaccountname$_BLOB_CORE_WINDOWS_NET
          value: $yourstorageaccountkey$
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
        volumeMounts:
        - mountPath: /usr/local/nvidia
          name: nvidia-driver
        - mountPath: /opt/ramdisk
          name: ramdisk
        - mountPath: /etc/resolv.conf
          name: resolv
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      nodeSelector:
        FragmentGPUJob: active
      volumes:
      - name: nvidia-driver
        hostPath:
          path: /opt/nvidia-driver/current
      - name: ramdisk
        hostPath:
          path: /mnt/ramdisk
      - name: resolv
        hostPath:
          path: /etc/resolv.conf
---
